# Generated by Django 5.0.7 on 2024-09-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amazon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=6)),
                ('re_password', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'Amazon',
            },
        ),
    ]
