# Generated by Django 5.0.7 on 2024-09-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazonapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
