# Generated by Django 5.0.7 on 2024-09-06 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amazonapp', '0005_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
    ]
