# Generated by Django 5.0.7 on 2024-09-06 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amazonapp', '0009_alter_product_description_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
    ]
