# Generated by Django 5.0.7 on 2024-09-09 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amazonapp', '0032_alter_order_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
