# Generated by Django 5.0.7 on 2024-09-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazonapp', '0038_alter_order_phone_alter_order_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.IntegerField(blank=True, default=None, max_length=10),
        ),
    ]
