# Generated by Django 5.0.7 on 2024-09-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazonapp', '0045_remove_order_address_remove_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
