# Generated by Django 5.0.7 on 2024-09-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazonapp', '0047_order_phone_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=None, default=1, max_length=50),
        ),
    ]
