# Generated by Django 5.0.7 on 2024-09-09 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amazonapp', '0053_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
