# Generated by Django 5.0.7 on 2024-09-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazonapp', '0055_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
