# Generated by Django 5.0.7 on 2024-09-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazonapp', '0059_alter_customer_phone_alter_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
