# Generated by Django 5.0.7 on 2024-09-09 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amazonapp', '0061_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='qunatity',
            new_name='quantity',
        ),
    ]
