# Generated by Django 5.0.7 on 2024-09-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazonapp', '0069_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.IntegerField(blank=True, default=2546),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=''),
        ),
    ]
