# Generated by Django 5.0.7 on 2024-09-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazonapp', '0077_alter_order_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.AddField(
            model_name='order',
            name='adress',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
