# Generated by Django 5.0.7 on 2024-09-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazonapp', '0078_remove_order_phone_order_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
