# Generated by Django 5.0.7 on 2024-09-10 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amazonapp', '0079_order_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='adress',
        ),
    ]
